using System.Text;
using FormWorks.Templates.Analysis;
using FormWorks.Templates.Model;

namespace FormWorks.Templates.Emit;

/// <summary>A guard the navigator could not express in C#, and why.</summary>
public sealed record UnroutableGuard(string SourceField, string Detail);

public sealed record NavigatorResult(string Code, IReadOnlyList<UnroutableGuard> Unroutable);

/// <summary>
/// Writes the routing table as typed C#.
///
/// The table could have been emitted as data and read by a shared interpreter, but the
/// whole estate references only 22 distinct fields in its routing guards, so an
/// interpreter would buy generality nobody needs and trade compiler checking for
/// reflection. Generated code lets the compiler check every field reference and lets a
/// developer step through a routing decision when a form sends an agent to the wrong page.
///
/// Order is load bearing. The table is an ordered chain and the first match wins, exactly
/// as the source elseif chain does, so the emitted ifs keep their order and return early.
/// </summary>
public static class NavigatorEmitter
{
    public static NavigatorResult Emit(
        TemplateDocument doc,
        IReadOnlyList<PageEmitModel> pages,
        RouteTableReport routes,
        HouseStyle style,
        string className,
        string reportClassName)
    {
        var fields = BuildFieldIndex(pages);
        var owners = BuildOwnerIndex(pages);
        var named = BuildNameSet(pages);
        var unroutable = new List<UnroutableGuard>();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"//     Generated from {doc.FolderName}.");
        sb.AppendLine("//     Do not edit. Regenerate instead; edits here are lost.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"using {style.ModelsNamespace};");
        sb.AppendLine();
        sb.AppendLine($"namespace {style.ViewsNamespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Where each button on a {Escape(doc.FolderName)} report goes next.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");

        foreach (var group in routes.Routes
                     .Where(r => r.SourceField.Length > 0)
                     .GroupBy(r => r.SourceField, StringComparer.Ordinal))
        {
            var method = MethodName(group.Key);
            var ordered = group.ToList();

            sb.AppendLine();
            sb.AppendLine($"    /// <summary>{Escape(group.Key)}. The first matching route wins, as in the template.</summary>");
            sb.AppendLine($"    public static string? {method}({reportClassName} report)");
            sb.AppendLine("    {");

            foreach (var route in ordered)
            {
                var condition = Condition(route, fields, owners, named, unroutable);
                var target = "//" + RoutesEmitter.Route(TargetClass(route.ToPage, pages));

                if (condition is null)
                {
                    sb.AppendLine($"        return \"{target}\";");
                    break;
                }

                sb.AppendLine($"        if ({condition})");
                sb.AppendLine($"            return \"{target}\";");
                sb.AppendLine();
            }

            if (ordered.All(r => Condition(r, fields, owners, named, []) is not null))
                sb.AppendLine("        return null;");

            sb.AppendLine("    }");
        }

        EmitPath(sb, pages, routes, reportClassName);

        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Lua's string.sub is one-based and inclusive at both ends, so a slice of 1 to 6");
        sb.AppendLine("    /// is six characters starting at the first. Getting that wrong by one silently");
        sb.AppendLine("    /// routes a whole client's cases to the wrong page.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    private static bool Slice(string? value, int from, int to, string literal)");
        sb.AppendLine("        => value is not null");
        sb.AppendLine("           && value.Length >= to");
        sb.AppendLine("           && string.Equals(value[(from - 1)..to], literal, StringComparison.Ordinal);");
        sb.AppendLine("}");

        return new NavigatorResult(sb.ToString(), unroutable);
    }

    /// <summary>
    /// The pages the agent will actually pass through, given the answers so far.
    ///
    /// Derived by walking the same routing the buttons use, so the step strip and the
    /// navigation cannot disagree. An outcome that skips a page drops that page out of the
    /// strip rather than offering a step the form will never visit.
    /// </summary>
    private static void EmitPath(
        StringBuilder sb, IReadOnlyList<PageEmitModel> pages, RouteTableReport routes,
        string reportClassName)
    {
        var routed = routes.Routes.Select(r => r.SourceField).ToHashSet(StringComparer.Ordinal);
        var entry = "//" + RoutesEmitter.Route(pages[0].ClassName);

        sb.AppendLine();
        sb.AppendLine("    /// <summary>Where a form starts.</summary>");
        sb.AppendLine($"    public const string EntryRoute = \"{entry}\";");

        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// The pages this report will pass through, in order, given the answers so far.");
        sb.AppendLine("    /// Recomputed rather than stored, so it follows the answers as they change.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static IReadOnlyList<(string Title, string Route)> Path({reportClassName} report)");
        sb.AppendLine("    {");
        sb.AppendLine("        var path = new List<(string, string)>();");
        sb.AppendLine("        var seen = new HashSet<string>(StringComparer.Ordinal);");
        sb.AppendLine("        string? route = EntryRoute;");
        sb.AppendLine();
        sb.AppendLine("        // A form that loops back to a page already visited ends the strip there");
        sb.AppendLine("        // rather than walking the loop forever.");
        sb.AppendLine("        while (route is not null && seen.Add(route))");
        sb.AppendLine("        {");
        sb.AppendLine("            path.Add((TitleOf(route), route));");
        sb.AppendLine("            route = Forward(report, route);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return path;");
        sb.AppendLine("    }");

        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// The button that carries a page forward. A page with several takes the one the");
        sb.AppendLine("    /// template captions Next, because the others go back or sideways.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    private static string? Forward({reportClassName} report, string route) => route switch");
        sb.AppendLine("    {");

        foreach (var page in pages)
        {
            var forward = ForwardAction(page, routed);
            if (forward is null) continue;

            sb.AppendLine($"        \"//{RoutesEmitter.Route(page.ClassName)}\" => {MethodName(forward)}(report),");
        }

        sb.AppendLine("        _ => null");
        sb.AppendLine("    };");

        sb.AppendLine();
        sb.AppendLine("    private static string TitleOf(string route) => route switch");
        sb.AppendLine("    {");
        foreach (var page in pages)
        {
            var title = page.Page.Title is { Length: > 0 } t ? t : page.PageName;
            sb.AppendLine($"        \"//{RoutesEmitter.Route(page.ClassName)}\" => \"{Escape(title).Replace("\"", "\\\"")}\",");
        }
        sb.AppendLine("        _ => route");
        sb.AppendLine("    };");
    }

    /// <summary>The condition for one route, or null when it is unconditional.</summary>
    private static string? Condition(
        Route route, IReadOnlyDictionary<string, string> fields,
        IReadOnlyDictionary<string, string> owners, IReadOnlySet<string> named,
        IList<UnroutableGuard> unroutable)
    {
        if (route.Own.Count == 0) return null;

        var parts = new List<string>();

        foreach (var condition in route.Own)
        {
            var alternatives = new List<string>();

            foreach (var conjunction in condition.AnyOf)
            {
                var atoms = conjunction.Select(a => Atom(a, fields, owners, named, route, unroutable)).ToList();
                if (atoms.Any(a => a is null)) return "false /* unroutable */";
                alternatives.Add(atoms.Count == 1 ? atoms[0]! : "(" + string.Join(" && ", atoms) + ")");
            }

            if (alternatives.Count == 0) return "false /* unroutable */";
            parts.Add(alternatives.Count == 1 ? alternatives[0] : "(" + string.Join(" || ", alternatives) + ")");
        }

        return string.Join(" && ", parts);
    }

    private static string? Atom(
        Guard guard, IReadOnlyDictionary<string, string> fields,
        IReadOnlyDictionary<string, string> owners, IReadOnlySet<string> named,
        Route route, IList<UnroutableGuard> unroutable)
    {
        string? path;

        // Lua's self-reference: the field whose handler this is. It is not a name to look
        // up, so resolving it needs the script's owner rather than the field index.
        if (guard.Field == "this")
        {
            if (!owners.TryGetValue(route.SourceField, out path))
            {
                unroutable.Add(new UnroutableGuard(
                    route.SourceField, "'this' names a control that holds no answer"));
                return null;
            }
        }
        else if (!fields.TryGetValue(guard.Field, out path))
        {
            // A name that exists but answers nothing is a different fault from a name that
            // does not exist, and only one of them is the template's mistake.
            unroutable.Add(new UnroutableGuard(
                route.SourceField,
                named.Contains(guard.Field)
                    ? $"'{guard.Field}' names a control that holds no answer"
                    : $"no field named '{guard.Field}'"));
            return null;
        }

        var literal = guard.Literal.Replace("\\", "\\\\").Replace("\"", "\\\"");

        if (guard.IsPrefixTest)
        {
            var test = $"Slice(report.{path}, {guard.From}, {guard.To}, \"{literal}\")";
            return guard.IsNegated ? $"!{test}" : test;
        }

        var comparison = $"string.Equals(report.{path}, \"{literal}\", StringComparison.Ordinal)";
        return guard.IsNegated ? $"!{comparison}" : comparison;
    }

    /// <summary>
    /// Element name to a path on the report.
    ///
    /// Scripts name a field by its short name, which usually lands on the section wrapping
    /// a control rather than the control itself, so a name with no answer of its own
    /// resolves to its single answering descendant. Outermost wins, which is what a script
    /// sees.
    /// </summary>
    private static Dictionary<string, string> BuildFieldIndex(IReadOnlyList<PageEmitModel> pages)
    {
        var index = new Dictionary<string, string>(StringComparer.Ordinal);

        foreach (var page in pages)
        {
            foreach (var field in page.AllFields)
            {
                var path = $"{page.PageName}.{field.PropertyName}";

                for (var node = field.Source; node is not null && !node.IsPage; node = node.Parent)
                {
                    foreach (var key in new[] { node.ElementName, node.Alias })
                        if (!string.IsNullOrEmpty(key))
                            index.TryAdd(key, path);
                }
            }
        }

        return index;
    }

    /// <summary>
    /// The action that takes a page forward: the one captioned Next where there is one,
    /// otherwise the only routed button, otherwise none.
    /// </summary>
    private static string? ForwardAction(PageEmitModel page, IReadOnlySet<string> routed)
    {
        var candidates = page.Actions
            .Select(a => a.Source.Label)
            .Where(routed.Contains)
            .ToList();

        if (candidates.Count == 0) return null;

        var next = page.Actions.FirstOrDefault(a =>
            routed.Contains(a.Source.Label)
            && a.Title.Contains("Next", StringComparison.OrdinalIgnoreCase));

        return next?.Source.Label ?? candidates[0];
    }

    /// <summary>
    /// The full name of each answering field to its path on the report, so a handler's own
    /// field can be found from the script that owns it.
    /// </summary>
    private static Dictionary<string, string> BuildOwnerIndex(IReadOnlyList<PageEmitModel> pages)
    {
        var index = new Dictionary<string, string>(StringComparer.Ordinal);

        foreach (var page in pages)
            foreach (var field in page.AllFields)
                index.TryAdd(field.Source.Label, $"{page.PageName}.{field.PropertyName}");

        return index;
    }

    /// <summary>Every name a script could use, whether it answers anything or not.</summary>
    private static HashSet<string> BuildNameSet(IReadOnlyList<PageEmitModel> pages)
    {
        var names = new HashSet<string>(StringComparer.Ordinal);

        foreach (var page in pages)
            foreach (var node in page.Page.DescendantsAndSelf())
                foreach (var key in new[] { node.ElementName, node.Alias })
                    if (!string.IsNullOrEmpty(key))
                        names.Add(key);

        return names;
    }

    private static string TargetClass(string toPage, IReadOnlyList<PageEmitModel> pages)
        => pages.FirstOrDefault(p =>
               string.Equals(p.PageName, PageEmitModelBuilder.Identifier(toPage), StringComparison.Ordinal))
               ?.ClassName
           ?? PageEmitModelBuilder.Identifier(toPage) + "Page";

    /// <summary>
    /// Qualified by its full path. Nine of the sixteen pages call their button
    /// "NextButton", so the leaf name alone collides - and a page with more than one
    /// Next (one per branch, say) also collides on page name alone, so every ancestor
    /// down to the page is kept rather than just the page name.
    /// </summary>
    public static string MethodName(string sourceField)
    {
        var parts = sourceField.Split('.');
        return string.Concat(parts.Select(PageEmitModelBuilder.Identifier));
    }

    private static string Escape(string text)
        => text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}
