using System.Text;
using FormWorks.Templates.Model;

namespace FormWorks.Templates.Emit;

/// <summary>
/// Writes the report: one object holding every page's answers for a template.
///
/// Answers cannot live on the pages that collect them. Every outcome page's Next button
/// routes on the case reference, which is captured on the Job Sheet, and view models are
/// transient so anything held on one is gone the moment the agent navigates. This is the
/// same conclusion the multi-page proof of concept reached; the difference is that it is
/// now generated rather than hand-written.
/// </summary>
public static class ReportEmitter
{
    public static string Emit(
        TemplateDocument doc, IReadOnlyList<PageEmitModel> pages, HouseStyle style, string className,
        ControlVocabulary vocabulary)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"//     Generated from {doc.FolderName}.");
        sb.AppendLine("//     Do not edit. Regenerate instead; edits here are lost.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Globalization;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using CommunityToolkit.Mvvm.ComponentModel;");
        sb.AppendLine($"using {style.FormsNamespace};");
        sb.AppendLine();
        sb.AppendLine($"namespace {style.ModelsNamespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Every answer on a {Escape(doc.FolderName)} report.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public partial class {className} : ObservableObject");
        sb.AppendLine("{");

        sb.AppendLine();
        sb.AppendLine("    private bool _showValidationErrors;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Whether the agent is being shown what is wrong. Off until asked for.");
        sb.AppendLine("    ///");
        sb.AppendLine("    /// FormWorks ran every rule at a submission trigger rather than as the agent");
        sb.AppendLine("    /// typed, so a form does not open covered in red. Nothing sets this yet:");
        sb.AppendLine("    /// submission will, once it exists, after checking whether any field is");
        sb.AppendLine("    /// invalid and stopping if so.");
        sb.AppendLine("    ///");
        sb.AppendLine("    /// The rules themselves run continuously and the messages stay current, so a");
        sb.AppendLine("    /// field clears the moment it is answered rather than at the next submission.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public bool ShowValidationErrors");
        sb.AppendLine("    {");
        sb.AppendLine("        get => _showValidationErrors;");
        sb.AppendLine("        set => SetProperty(ref _showValidationErrors, value);");
        sb.AppendLine("    }");

        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// What a person decided about a field's shown or usable state, where the");
        sb.AppendLine("    /// generator could not, by the field's FormWorks name.");
        sb.AppendLine("    ///");
        sb.AppendLine("    /// Without this there are two answers to whether a field is shown and they");
        sb.AppendLine("    /// disagree: the page asks the hand-written rule, while the generated code asks");
        sb.AppendLine("    /// a table that has never heard of it. A section would then disappear from the");
        sb.AppendLine("    /// screen while its answers stayed in the report and its rules kept firing.");
        sb.AppendLine("    ///");
        sb.AppendLine("    /// Not saved with the report: it is a decision about the form, recomputed from");
        sb.AppendLine("    /// the answers every time the rules run.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [JsonIgnore]");
        sb.AppendLine("    public Dictionary<string, bool> Decided { get; } = new(StringComparer.Ordinal);");

        foreach (var page in pages)
        {
            sb.AppendLine();
            sb.AppendLine($"    /// <summary>{Escape(PageTitle(page))}</summary>");
            // Settable, not get-only. System.Text.Json skips read-only properties of
            // complex type on deserialise, so a get-only page saves correctly and comes
            // back empty with no error anywhere.
            sb.AppendLine($"    public {page.AnswersClassName} {page.PageName} {{ get; set; }} = new();");
        }

        EmitValidity(sb, pages);
        EmitExchange(sb, pages, vocabulary);

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Whether every validated field, across every page, is currently error-free.
    ///
    /// Only accurate once every page has had its rules run at least once: a page nobody has
    /// opened has never set its fields' error state, valid or not, so its answers read as
    /// clean here whether or not they actually are. FormRoutes.ValidateAll runs every page
    /// first and is the intended way to check this, rather than reading it cold.
    /// </summary>
    private static void EmitValidity(StringBuilder sb, IReadOnlyList<PageEmitModel> pages)
    {
        var errors = pages
            .SelectMany(p => p.Validated.Select(field => $"{p.PageName}.{field}Error"))
            .ToList();

        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Whether every validated field, across every page, is currently error-free.");
        sb.AppendLine("    ///");
        sb.AppendLine("    /// Only accurate once every page has had its rules run at least once - see");
        sb.AppendLine("    /// FormRoutes.ValidateAll, which does that before reading this.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [JsonIgnore]");

        if (errors.Count == 0)
        {
            sb.AppendLine("    public bool IsValid => true;");
            return;
        }

        sb.AppendLine("    public bool IsValid =>");
        for (var i = 0; i < errors.Count; i++)
        {
            var end = i == errors.Count - 1 ? ";" : " &&";
            sb.AppendLine($"        {errors[i]} is null{end}");
        }
    }

    /// <summary>
    /// Reading a job in and writing the answers back out, both keyed by the fully
    /// qualified FormWorks name.
    ///
    /// That name is the contract with the portal, because the CMS exports against it. It
    /// is not derivable from the generated property: nothing about Borrower1Name says it
    /// came from JobSheet.JobSheetDetails.Borrower1.Name. Only the template knows, so it
    /// is written down here at generation time.
    ///
    /// Both directions come from one list, so they cannot drift apart.
    /// </summary>
    private static void EmitExchange(
        StringBuilder sb, IReadOnlyList<PageEmitModel> pages, ControlVocabulary vocabulary)
    {
        var fields = pages
            .SelectMany(p => p.AllFields.Select(f => (Page: p, Field: f)))
            .ToList();

        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Applies a job's values, returning anything that did not fit rather than throwing");
        sb.AppendLine("    /// or ignoring it. One bad field should not lose the job, and a field that quietly");
        sb.AppendLine("    /// failed to load is found by an agent at a door.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public IReadOnlyList<FieldProblem> Apply(IReadOnlyDictionary<string, string?> values)");
        sb.AppendLine("    {");
        sb.AppendLine("        var problems = new List<FieldProblem>();");
        sb.AppendLine();
        sb.AppendLine("        foreach (var (field, value) in values)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (field)");
        sb.AppendLine("            {");

        foreach (var (page, field) in fields)
        {
            var target = $"{page.PageName}.{field.PropertyName}";
            sb.AppendLine($"                case \"{Escape(field.Source.Label)}\":");

            switch (field.Mapping!.ClrType)
            {
                case "string":
                    sb.AppendLine($"                    {target} = value ?? string.Empty;");
                    break;
                case "string?":
                    sb.AppendLine($"                    {target} = string.IsNullOrEmpty(value) ? null : value;");
                    break;
                case "bool":
                    sb.AppendLine($"                    if (TryReadBoolean(value, out var b{FieldId(target)})) {target} = b{FieldId(target)};");
                    sb.AppendLine($"                    else problems.Add(Unreadable(field, value, \"a yes or no value\"));");
                    break;
                case "DateTime?":
                    // An empty value is an unanswered field, not a bad one.
                    sb.AppendLine($"                    if (string.IsNullOrWhiteSpace(value)) {target} = null;");
                    sb.AppendLine($"                    else if (TryReadDate(value, out var d{FieldId(target)})) {target} = d{FieldId(target)};");
                    sb.AppendLine($"                    else problems.Add(Unreadable(field, value, \"a date\"));");
                    break;
                case "TimeSpan?":
                    sb.AppendLine($"                    if (string.IsNullOrWhiteSpace(value)) {target} = null;");
                    sb.AppendLine($"                    else if (TryReadTime(value, out var t{FieldId(target)})) {target} = t{FieldId(target)};");
                    sb.AppendLine($"                    else problems.Add(Unreadable(field, value, \"a time\"));");
                    break;
            }

            sb.AppendLine("                    break;");
        }

        sb.AppendLine("                default:");
        sb.AppendLine("                    problems.Add(new FieldProblem(");
        sb.AppendLine("                        FieldProblemKind.UnknownField, field, value,");
        sb.AppendLine("                        \"no field of this name on this template\"));");
        sb.AppendLine("                    break;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        OnOpened();");
        sb.AppendLine("        return problems;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Where a template's OnOpen handlers are written, in the hand-written half of");
        sb.AppendLine("    /// this class. Runs once, after a job's values are applied - not once per page,");
        sb.AppendLine("    /// since the report opens once for the whole job. Listed per template in");
        sb.AppendLine("    /// Remaining.md under \"Answers the form fills in\".");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    partial void OnOpened();");

        sb.AppendLine();
        sb.AppendLine("    /// <summary>Every answer, keyed the way the portal expects.</summary>");
        sb.AppendLine("    public IReadOnlyDictionary<string, string?> ToFieldValues() => new Dictionary<string, string?>");
        sb.AppendLine("    {");
        foreach (var (page, field) in fields)
        {
            var source = $"{page.PageName}.{field.PropertyName}";
            var text = field.Mapping!.ClrType switch
            {
                "string" or "string?" => source,
                "bool" => $"{source} ? \"true\" : \"false\"",
                // Null stays null. An unanswered date must not leave as today's.
                "DateTime?" => $"{source}?.ToString(\"{vocabulary.DateOutputFormat}\", CultureInfo.InvariantCulture)",
                "TimeSpan?" => $"{source}?.ToString(@\"{vocabulary.TimeOutputFormat}\", CultureInfo.InvariantCulture)",
                _ => source
            };
            sb.AppendLine($"        [\"{Escape(field.Source.Label)}\"] = {text},");
        }
        sb.AppendLine("    };");

        EmitReaders(sb, vocabulary);
    }

    private static void EmitReaders(StringBuilder sb, ControlVocabulary vocabulary)
    {
        var dates = string.Join(", ", vocabulary.DateInputFormats.Select(f => $"\"{f}\""));
        var times = string.Join(", ", vocabulary.TimeInputFormats.Select(f => $"@\"{f}\""));
        var booleans = string.Join(", ", vocabulary.BooleanInputs
            .Select(kv => $"[\"{kv.Key}\"] = {kv.Value.ToString().ToLowerInvariant()}"));

        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Explicit formats and an invariant culture, deliberately. A locale-sensitive");
        sb.AppendLine("    /// parse turns the third of April into the fourth of March without complaining.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    private static readonly string[] DateFormats = [{dates}];");
        sb.AppendLine();
        sb.AppendLine($"    private static readonly string[] TimeFormats = [{times}];");
        sb.AppendLine();
        sb.AppendLine("    private static readonly Dictionary<string, bool> Booleans =");
        sb.AppendLine("        new(StringComparer.OrdinalIgnoreCase) { " + booleans + " };");
        sb.AppendLine();
        sb.AppendLine("    private static bool TryReadDate(string? value, out DateTime result)");
        sb.AppendLine("        => DateTime.TryParseExact(value, DateFormats, CultureInfo.InvariantCulture,");
        sb.AppendLine("            DateTimeStyles.AllowWhiteSpaces, out result);");
        sb.AppendLine();
        sb.AppendLine("    private static bool TryReadTime(string? value, out TimeSpan result)");
        sb.AppendLine("        => TimeSpan.TryParseExact(value, TimeFormats, CultureInfo.InvariantCulture, out result);");
        sb.AppendLine();
        sb.AppendLine("    private static bool TryReadBoolean(string? value, out bool result)");
        sb.AppendLine("    {");
        sb.AppendLine("        result = false;");
        sb.AppendLine("        return value is not null && Booleans.TryGetValue(value.Trim(), out result);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static FieldProblem Unreadable(string field, string? value, string expected)");
        sb.AppendLine("        => new(FieldProblemKind.UnreadableValue, field, value, $\"not {expected}\");");
    }

    /// <summary>A unique suffix per case, since C# scopes switch locals to the whole block.</summary>
    private static string FieldId(string target) => target.Replace(".", "");

    private static string PageTitle(PageEmitModel page)
        => page.Page.Title is { Length: > 0 } t ? t : page.PageName;

    private static string Escape(string text)
        => text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").ReplaceLineEndings(" ").Trim();
}
