using System.Text;
using FormWorks.Templates.Analysis;
using FormWorks.Templates.Model;

namespace FormWorks.Templates.Emit;

/// <param name="Unexpressible">Rules whose condition could not be recovered.</param>
/// <param name="RefusedFields">
/// Every field with at least one refused rule, by label. The single source of truth for
/// "did this field's validation actually get generated" - Remaining.md and the worklist
/// both read this rather than re-deriving their own answer, so a refusal reason this
/// class discovers (a condition it will not honour, not just one it could not parse)
/// cannot go unlisted while the field quietly validates nothing.
/// </param>
/// <param name="Wording">
/// Rules that work but say the wrong thing, because the template built the message at
/// runtime and the field's caption stands in. Separate from Unexpressible: one is a rule
/// that is missing, the other a rule that is present and inarticulate.
/// </param>
public sealed record ValidatorResult(
    string Code,
    IReadOnlyDictionary<string, IReadOnlyList<string>> ErrorPropertiesByPage,
    int RulesEmitted,
    IReadOnlyList<string> Unexpressible,
    IReadOnlySet<string> RefusedFields,
    IReadOnlyList<(string Field, string Expression, string Caption)> Wording);

/// <summary>
/// Writes what makes each field invalid, as typed C#.
///
/// Same reasoning as the navigator: the rules reference only a small vocabulary of
/// comparisons, so generated code lets the compiler check every field reference and lets
/// a developer step through a rule when a form refuses to accept an answer. An
/// interpreter would trade that for reflection and buy nothing.
///
/// Rules are sparse. A third of fields carry one, so a property per validated field costs
/// a hundred members on a template rather than three hundred.
/// </summary>
public static class ValidatorEmitter
{
    public static ValidatorResult Emit(
        TemplateDocument doc,
        IReadOnlyList<PageEmitModel> pages,
        ValidationTableReport validation,
        HouseStyle style,
        string className,
        string reportClassName,
        string? visibilityClassName = null)
    {
        var paths = GuardRenderer.PathIndex(pages);
        var types = GuardRenderer.TypeIndex(pages);
        var owners = OwnerIndex(pages);
        var resolver = new NameResolver(doc);

        // A rule reading whether a field is shown names it the way the handler does, and
        // the state tables answer to elements rather than names, so it resolves from the
        // page the rule was written on.
        var nodes = doc.AllNodes
            .GroupBy(n => n.Label, StringComparer.Ordinal)
            .ToDictionary(g => g.Key, g => g.First(), StringComparer.Ordinal);
        var byPage = new Dictionary<string, IReadOnlyList<string>>(StringComparer.Ordinal);
        var unexpressible = new List<string>();
        var refusedFields = new HashSet<string>(StringComparer.Ordinal);
        var wording = new List<(string, string, string)>();
        var titles = pages
            .SelectMany(p => p.AllFields)
            .GroupBy(f => f.Source.Label, StringComparer.Ordinal)
            .ToDictionary(g => g.Key, g => g.First().Title, StringComparer.Ordinal);
        var emitted = 0;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"//     Generated from {doc.FolderName}.");
        sb.AppendLine("//     Do not edit. Regenerate instead; edits here are lost.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"using {style.ModelsNamespace};");
        sb.AppendLine();
        sb.AppendLine($"namespace {style.ViewsNamespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// What makes a field on a {Escape(doc.FolderName)} report invalid.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");

        foreach (var page in pages)
        {
            var rules = validation.Rules
                .Where(r => Owns(page, r.Field))
                .GroupBy(r => r.Field, StringComparer.Ordinal)
                .ToList();

            var properties = new List<string>();

            sb.AppendLine();
            sb.AppendLine($"    /// <summary>Rules for {Escape(PageTitle(page))}.</summary>");
            sb.AppendLine($"    public static void Validate{page.PageName}({reportClassName} report)");
            sb.AppendLine("    {");

            if (rules.Count == 0)
            {
                sb.AppendLine("        // The template states no rules for this page.");
            }
            else
            {
                sb.AppendLine($"        var answers = report.{page.PageName};");
                sb.AppendLine();
            }

            foreach (var group in rules)
            {
                if (!owners.TryGetValue(group.Key, out var property)) continue;

                var expressible = group.Where(r => r.FullyParsed && !HasUnreliableStateTest(r, nodes, resolver)).ToList();
                foreach (var refused in group.Where(r => !r.FullyParsed || HasUnreliableStateTest(r, nodes, resolver)))
                {
                    unexpressible.Add($"{refused.Field}: {string.Join(" AND ", refused.When)}");
                    refusedFields.Add(refused.Field);
                }

                if (expressible.Count == 0) continue;

                properties.Add(property + "Error");
                emitted += expressible.Count;

                sb.AppendLine($"        answers.{property}Error =");

                // First match wins, as an if/elseif chain does in the template.
                foreach (var rule in expressible)
                {
                    var from = nodes.GetValueOrDefault(group.Key);

                    var condition = GuardRenderer.Render(
                        rule.When, paths, group.Key, "IsShown",
                        name => resolver.Resolve(name, from)?.Label ?? name,
                        types);
                    sb.AppendLine($"            {condition}");
                    sb.AppendLine($"                ? {Literal(rule, titles, wording)}");
                    sb.AppendLine("                :");
                }

                sb.AppendLine("            null;");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            byPage[page.PageName] = properties;
        }

        EmitWholeForm(sb, pages, byPage, reportClassName);
        EmitHelpers(sb, reportClassName, visibilityClassName);

        sb.AppendLine("}");
        return new ValidatorResult(sb.ToString(), byPage, emitted, unexpressible, refusedFields, wording);
    }

    /// <summary>
    /// The whole form at once, for submission.
    ///
    /// Submission runs every rule, stops if anything is invalid, and only then shows the
    /// messages. Splitting "run the rules" from "is anything wrong" keeps that decision
    /// with the caller rather than burying it here.
    /// </summary>
    private static void EmitWholeForm(
        StringBuilder sb, IReadOnlyList<PageEmitModel> pages,
        IReadOnlyDictionary<string, IReadOnlyList<string>> byPage, string reportClassName)
    {
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Runs every page's rules.</summary>");
        sb.AppendLine($"    public static void ValidateAll({reportClassName} report)");
        sb.AppendLine("    {");
        foreach (var page in pages)
            sb.AppendLine($"        Validate{page.PageName}(report);");
        sb.AppendLine("    }");

        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Every field that is currently invalid, by its fully qualified FormWorks name,");
        sb.AppendLine("    /// with what it says. Empty means the form is ready to submit.");
        sb.AppendLine("    ///");
        sb.AppendLine("    /// Run ValidateAll first: this reports what the rules last decided, it does not");
        sb.AppendLine("    /// decide it.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static IReadOnlyList<(string Field, string Message)> Invalid({reportClassName} report)");
        sb.AppendLine("    {");
        sb.AppendLine("        var invalid = new List<(string, string)>();");

        foreach (var page in pages)
        {
            if (!byPage.TryGetValue(page.PageName, out var properties) || properties.Count == 0) continue;

            sb.AppendLine();
            foreach (var property in properties)
            {
                var field = page.AllFields.FirstOrDefault(f =>
                    string.Equals(f.PropertyName + "Error", property, StringComparison.Ordinal));

                var label = field?.Source.Label ?? property;
                sb.AppendLine($"        if (report.{page.PageName}.{property} is {{ }} {Local(page, property)})");
                sb.AppendLine($"            invalid.Add((\"{Escape(label)}\", {Local(page, property)}));");
            }
        }

        sb.AppendLine();
        sb.AppendLine("        return invalid;");
        sb.AppendLine("    }");
    }

    private static string Local(PageEmitModel page, string property)
        => "m" + page.PageName + property;

    private static void EmitHelpers(
        StringBuilder sb, string reportClassName, string? visibilityClassName)
    {
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Whether a field is currently shown. A rule very often only applies while its");
        sb.AppendLine("    /// field is visible, so the condition reads this.");
        sb.AppendLine("    /// </summary>");

        if (visibilityClassName is null)
        {
            sb.AppendLine("    ///");
            sb.AppendLine("    /// Visibility is not generated for this template, so everything counts as shown.");
            sb.AppendLine($"    private static bool IsShown({reportClassName} report, string field) => true;");
        }
        else
        {
            sb.AppendLine($"    private static bool IsShown({reportClassName} report, string field)");
            sb.AppendLine($"        => {visibilityClassName}.IsShown(report, field);");
        }

        sb.AppendLine();
        GuardRenderer.EmitSliceHelper(sb);
    }

    /// <summary>
    /// What the agent is told.
    ///
    /// Where the template computes the message, `this.title` is the field's own caption and
    /// is known here, so it is resolved rather than emitted as the word "this.title". A
    /// message built from a local cannot be resolved, so the field's caption stands in and
    /// the wording is reported for a person to write.
    /// </summary>
    private static string Literal(
        ValidationRule rule, IReadOnlyDictionary<string, string> titles,
        IList<(string, string, string)> reported)
    {
        if (rule.Message is not null) return $"\"{Escape(rule.Message)}\"";

        var caption = titles.GetValueOrDefault(rule.Field, rule.Field);

        if (rule.MessageExpression is "this.title" or "this.message")
            return $"\"{Escape(caption)}\"";

        reported.Add((rule.Field, rule.MessageExpression, caption));
        return $"\"{Escape(caption)}\"";
    }

    /// <summary>
    /// Whether a rule's condition reads a shown/enabled state IsShown cannot answer
    /// honestly: a *page's*, e.g. `SomePage.visible` (page visibility is deliberately not
    /// in the generated tables - which pages a form visits is recovered as routing instead,
    /// to avoid reporting the same decision twice), or an alias that does not resolve to
    /// anything at all.
    ///
    /// Both render as `IsShown(report, "&lt;name&gt;")` for a name the generated table has
    /// never heard of, and that table answers "shown" for any name it does not recognise -
    /// right for a field nothing ever hides, wrong here: it turns "only required while X"
    /// into "always required", silently. Refused instead, the same way any other guard the
    /// generator cannot honour is.
    /// </summary>
    private static bool HasUnreliableStateTest(
        ValidationRule rule, IReadOnlyDictionary<string, TemplateNode> nodes, NameResolver resolver)
    {
        var from = nodes.GetValueOrDefault(rule.Field);

        return rule.When
            .SelectMany(c => c.Atoms)
            .Where(g => g.IsStateTest)
            .Select(g => resolver.Resolve(g.Field == "this" ? rule.Field : g.Field, from))
            .Any(node => node is null || node.IsPage);
    }

    private static bool Owns(PageEmitModel page, string field)
        => page.AllFields.Any(f => string.Equals(f.Source.Label, field, StringComparison.Ordinal));

    private static Dictionary<string, string> OwnerIndex(IReadOnlyList<PageEmitModel> pages)
    {
        var index = new Dictionary<string, string>(StringComparer.Ordinal);

        foreach (var page in pages)
            foreach (var field in page.AllFields)
                if (field.PropertyName is { } name) index.TryAdd(field.Source.Label, name);

        return index;
    }

    private static string PageTitle(PageEmitModel page)
        => page.Page.Title is { Length: > 0 } t ? t : page.PageName;

    private static string Escape(string text)
        => text.Replace("\\", "\\\\").Replace("\"", "\\\"").ReplaceLineEndings(" ");
}
